"""
R410A heat pump COP model — runs inside Pyodide (numpy only, no scipy).

Refrigerant property lookup via a pre-computed .npz table generated by
generate_lookup.py (CoolProp).

Cycle states
------------
 1  Saturated vapour   @ evaporator pressure
 2  Superheated vapour @ evaporator pressure, T_evap_sat + 5 °C
 3s Isentropic discharge state @ condenser pressure (hypothetical)
 3  Actual discharge   @ condenser pressure, 75 % isentropic efficiency
 4  Saturated vapour   @ condenser pressure
 5  Saturated liquid   @ condenser pressure
 6  Subcooled liquid   @ condenser pressure, T_cond_sat − 2 °C
 7  Saturated mixture  @ evaporator pressure, h7 = h6  (isenthalpic expansion)

COP (cooling) = (h2 − h7) / (h3 − h2)

Public API
----------
    load_lut_from_bytes(raw_bytes)
    calculate_cop(T_supply_C, T_ambient_C)  → float | None
"""

import io
import numpy as np

# Module-level lookup table (populated once by load_lut_from_bytes)
_lut: dict = {}


# ── Lookup-table loader ───────────────────────────────────────────────────────

def load_lut_from_bytes(raw) -> None:
    """
    Load the .npz lookup table from raw bytes (Python bytes / bytearray /
    memoryview, or a Pyodide-proxied JS Uint8Array).
    """
    global _lut
    if hasattr(raw, "to_py"):          # Pyodide JS proxy → Python bytes
        raw = bytes(raw.to_py())
    data = np.load(io.BytesIO(bytes(raw)))
    _lut["T_sat_C"]   = data["T_sat_C"]
    _lut["P_sat"]     = data["P_sat"]
    _lut["h_f"]       = data["h_f"]
    _lut["h_g"]       = data["h_g"]
    _lut["s_f"]       = data["s_f"]
    _lut["s_g"]       = data["s_g"]
    _lut["T_super_C"] = data["T_super_C"]
    _lut["P_super"]   = data["P_super"]
    _lut["h_super"]   = data["h_super"]
    _lut["s_super"]   = data["s_super"]


# ── Internal interpolation helpers ────────────────────────────────────────────

def _sat(T_C: float, arr: np.ndarray) -> float:
    """Linearly interpolate a saturation property at temperature T_C [°C]."""
    return float(np.interp(T_C, _lut["T_sat_C"], arr))


def _T_sat_from_P(P_Pa: float) -> float:
    """Interpolate saturation temperature [°C] from pressure [Pa]."""
    return float(np.interp(P_Pa, _lut["P_sat"], _lut["T_sat_C"]))


def _superheat(T_C: float, P_Pa: float, grid: np.ndarray) -> float:
    """
    Bilinear interpolation in the superheated vapour property grid.

    Parameters
    ----------
    T_C   : temperature [°C]
    P_Pa  : absolute pressure [Pa]
    grid  : h_super or s_super, shape (n_T, n_P)
    """
    T_arr = _lut["T_super_C"]
    P_arr = _lut["P_super"]

    T_C  = float(np.clip(T_C,  T_arr[0], T_arr[-1]))
    P_Pa = float(np.clip(P_Pa, P_arr[0], P_arr[-1]))

    i = int(np.clip(np.searchsorted(T_arr, T_C) - 1,  0, len(T_arr) - 2))
    j = int(np.clip(np.searchsorted(P_arr, P_Pa) - 1, 0, len(P_arr) - 2))

    tx = (T_C  - T_arr[i]) / (T_arr[i + 1] - T_arr[i])
    ty = (P_Pa - P_arr[j]) / (P_arr[j + 1] - P_arr[j])

    return float(
        grid[i,     j    ] * (1 - tx) * (1 - ty)
      + grid[i + 1, j    ] * tx       * (1 - ty)
      + grid[i,     j + 1] * (1 - tx) * ty
      + grid[i + 1, j + 1] * tx       * ty
    )


def _find_T_isentropic(s_target: float, P_Pa: float):
    """
    Find the superheated temperature [°C] at pressure P_Pa where the
    refrigerant entropy equals s_target [J kg⁻¹ K⁻¹].

    Returns None if the target entropy is outside the table range.
    """
    T_arr  = _lut["T_super_C"]
    P_arr  = _lut["P_super"]
    s_grid = _lut["s_super"]

    T_sat = _T_sat_from_P(P_Pa)

    # Interpolate an entropy column at P_Pa
    j  = int(np.clip(np.searchsorted(P_arr, P_Pa) - 1, 0, len(P_arr) - 2))
    ty = (P_Pa - P_arr[j]) / (P_arr[j + 1] - P_arr[j])
    s_col = s_grid[:, j] * (1 - ty) + s_grid[:, j + 1] * ty

    # Keep only superheated, non-NaN rows
    mask = (T_arr > T_sat + 0.1) & np.isfinite(s_col)
    if not np.any(mask):
        return None

    T_v = T_arr[mask]
    s_v = s_col[mask]

    # Entropy increases monotonically with T at constant P → safe to interp
    if s_target < s_v[0] or s_target > s_v[-1]:
        return None

    return float(np.interp(s_target, s_v, T_v))


# ── Public API ────────────────────────────────────────────────────────────────

def calculate_cop(T_supply_C: float, T_ambient_C: float):
    """
    Calculate the refrigeration COP for the R410A vapour-compression cycle.

    Parameters
    ----------
    T_supply_C  : supply-air temperature delivered to the conditioned space [°C]
                  (fixed at 12 °C in the web tool)
    T_ambient_C : outdoor ambient (dry-bulb) temperature [°C]

    Returns
    -------
    float  — COP  (> 0)
    None   — cycle is thermodynamically infeasible (condenser colder than
             evaporator, or table look-up out of range)
    """
    if not _lut:
        raise RuntimeError("Lookup table not loaded. Call load_lut_from_bytes() first.")

    T_lo = float(_lut["T_sat_C"][0])  + 0.5
    T_hi = float(_lut["T_sat_C"][-1]) - 0.5

    # Saturation temperatures
    T_evap = float(np.clip(T_supply_C  - 4.0, T_lo, T_hi))
    T_cond = float(np.clip(T_ambient_C + 7.0, T_lo, T_hi))

    P_evap = float(np.interp(T_evap, _lut["T_sat_C"], _lut["P_sat"]))
    P_cond = float(np.interp(T_cond, _lut["T_sat_C"], _lut["P_sat"]))

    if P_cond <= P_evap:
        return None   # condenser colder than evaporator — infeasible

    # State 1 — saturated vapour @ evaporator pressure (reference only)
    # h1 = _sat(T_evap, _lut["h_g"])

    # State 2 — 5 °C of superheat @ evaporator pressure
    T2 = T_evap + 5.0
    h2 = _superheat(T2, P_evap, _lut["h_super"])
    s2 = _superheat(T2, P_evap, _lut["s_super"])

    # State 3s — isentropic compression to condenser pressure
    T3s = _find_T_isentropic(s2, P_cond)
    if T3s is None:
        return None
    h3s = _superheat(T3s, P_cond, _lut["h_super"])

    # State 3 — actual discharge (75 % isentropic efficiency)
    ETA_ISEN = 0.75
    h3 = h2 + (h3s - h2) / ETA_ISEN

    if h3 <= h2:
        return None

    # State 6 — subcooled liquid, 2 °C below condenser saturation temp
    T6 = float(np.clip(T_cond - 2.0, T_lo, T_hi))
    h6 = _sat(T6, _lut["h_f"])   # h_f(T6) is a good approximation

    # State 7 — isenthalpic expansion to evaporator pressure
    h7 = h6

    # COP
    cop = (h2 - h7) / (h3 - h2)
    return float(cop) if cop > 0 else None
